// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3SktgqqBU3DdOAQ0QiH_I9SgxteAw1Mo',
    appId: '1:627608284269:web:b0a9da2c98c2b70e7fe364',
    messagingSenderId: '627608284269',
    projectId: 'seldura-firestore-demo',
    authDomain: 'seldura-firestore-demo.firebaseapp.com',
    storageBucket: 'seldura-firestore-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25_ZMqdwyCOtLU2TkKLbs2dToz6hkAg4',
    appId: '1:627608284269:android:74931eb876f2c8da7fe364',
    messagingSenderId: '627608284269',
    projectId: 'seldura-firestore-demo',
    storageBucket: 'seldura-firestore-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQuwtQnrmpBIW-FvtzubhNIX1rDJkbOng',
    appId: '1:949802881102:ios:3554745e8cdc66cbf7331f',
    messagingSenderId: '949802881102',
    projectId: 'seldura-firebase-demo',
    storageBucket: 'seldura-firebase-demo.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );
}